### ISSUE TITLE
semi.txt in ImageSets

### ISSUE THREAD

**Issue by XxxuLimei** [hailanyi/VirConv#29]
Thanks for the awesome work!
When I run`python3 -m pcdet.datasets.kitti.kitti_datasetsemi create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml` in terminal, some errors occured:
```
Traceback (most recent call last):
  File "/home/xilm/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xilm/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xilm/fuxian/VirConv/pcdet/datasets/kitti/kitti_datasetsemi.py", line 546, in <module>
    create_kitti_infos(
  File "/home/xilm/fuxian/VirConv/pcdet/datasets/kitti/kitti_datasetsemi.py", line 512, in create_kitti_infos
    dataset.set_split(trainsemi_split)
  File "/home/xilm/fuxian/VirConv/pcdet/datasets/kitti/kitti_datasetsemi.py", line 98, in set_split
    self.sample_id_list = self.include_id_list()
  File "/home/xilm/fuxian/VirConv/pcdet/datasets/kitti/kitti_datasetsemi.py", line 56, in include_id_list
    for i in ample_id_list_semi:
TypeError: 'NoneType' object is not iterable
```
It seems that I don't have the `semi.txt` file in ImageSets. May I ask for a `semi.txt`'s download link?
Thx:)

**Comment by hailanyi** [comment]
Indeed, we have provided the semi.txt in this repo, please check the [here](https://github.com/hailanyi/VirConv/blob/master/data/kitti/ImageSets/semi.txt).

**Comment by XxxuLimei** [comment]
Oh, I see, thank you!
By the way, when I run the train.py, I met the problem
```
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```
Would you like to give me some advice to solve this problem?

**Comment by hailanyi** [comment]
I have no idea, for the CUDA error, please check the cuda environment.

**Comment by XxxuLimei** [comment]
Okay，anyway，thanks!!!
