### ISSUE TITLE
RGB virtual Points

### ISSUE THREAD

**Issue by Soodep** [hailanyi/VirConv#33]
After generating the virtual point using PENet, where are those virtual points placed or output in the directory. My assumption is, looking at the directory structure, for each lidar frame or scene ( for instance 000009.bin, 000009.png)  the virtual points are generated separately for each object found in the scene (  000009_Car_0.bin, 000009_Car_1.bin, 000009_Car_2.bin) . Could you please explain it throughly.

**Comment by ck-png** [comment]
When I run the python3 main.py --detpath ../../data/kitti/semi, it shows the following mistakes:
Traceback (most recent call last):
  File "/home/avl1/ck/VirConv/tools/PENet/main.py", line 482, in <module>
    main()
  File "/home/avl1/ck/VirConv/tools/PENet/main.py", line 394, in main
    iterate("test_completion", args, test_loader, model, None, logger, 0)
  File "/home/avl1/ck/VirConv/tools/PENet/main.py", line 266, in iterate
    vis_utils.save_depth_as_points(pred, i, args.detpath)
  File "/home/avl1/ck/VirConv/tools/PENet/vis_utils.py", line 150, in save_depth_as_points
    final_points = depth2pointsrgbp(depth, image, calib, lidar)
  File "/home/avl1/ck/VirConv/tools/PENet/dataloaders/my_loader.py", line 403, in depth2pointsrgbp
    new_p = la_sampling2(new_p)
  File "/home/avl1/ck/VirConv/tools/PENet/dataloaders/my_loader.py", line 251, in la_sampling2
    return np.concatenate([finals[:, 8:11], finals[:, 3:8]], -1)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
