### ISSUE TITLE
not implemented for CPU ONLY build.

### ISSUE THREAD

**Issue by LSH9832** [hailanyi/VirConv#48]
I followed the installation step but still met an error while running test,py, do you know why this happens?
```bash
Traceback (most recent call last):
  File "test.py", line 191, in <module>
    main()
  File "test.py", line 187, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "test.py", line 63, in eval_single_ckpt
    eval_utils.eval_one_epoch(
  File "/home/ros/code/VirConv/tools/eval_utils/eval_utils.py", line 61, in eval_one_epoch
    pred_dicts, ret_dict, batch_dict = model(batch_dict)
  File "/home/ros/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ros/code/VirConv/pcdet/models/detectors/voxel_rcnn.py", line 10, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/ros/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ros/code/VirConv/pcdet/models/backbones_3d/spconv_backbone.py", line 657, in forward
    newx_conv1 = self.vir_conv1(newinput_sp_tensor, batch_size, calib, 1, self.x_trans_train, trans_param)
  File "/home/ros/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ros/code/VirConv/pcdet/models/backbones_3d/spconv_backbone.py", line 212, in forward
    d3_feat1 = self.d3_conv1(sp_tensor)
  File "/home/ros/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ros/.local/lib/python3.8/site-packages/spconv-2.3.6-py3.8-linux-x86_64.egg/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/home/ros/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ros/.local/lib/python3.8/site-packages/spconv-2.3.6-py3.8-linux-x86_64.egg/spconv/pytorch/conv.py", line 755, in forward
    return self._conv_forward(self.training,
  File "/home/ros/.local/lib/python3.8/site-packages/spconv-2.3.6-py3.8-linux-x86_64.egg/spconv/pytorch/conv.py", line 297, in _conv_forward
    raise e
  File "/home/ros/.local/lib/python3.8/site-packages/spconv-2.3.6-py3.8-linux-x86_64.egg/spconv/pytorch/conv.py", line 284, in _conv_forward
    outids, indice_pairs, indice_pair_num = ops.get_indice_pairs(
  File "/home/ros/.local/lib/python3.8/site-packages/spconv-2.3.6-py3.8-linux-x86_64.egg/spconv/pytorch/ops.py", line 156, in get_indice_pairs
    num_act_out = SpconvOps.get_indice_pairs(alloc,
RuntimeError: /io/build/temp.linux-x86_64-cpython-38/spconv/build/core_cc/src/csrc/sparse/all/SpconvOps/SpconvOps_get_indice_pairs.cc(65)
not implemented for CPU ONLY build.
```

**Comment by ZhaoKezzz** [comment]
I solved this problem through the following steps:
uninstall the packges: spconv, spconv-cu###,cumm and cumm-cu###.
install spconv-cu###.
$rm -rf build
$python setup.py develop
