### ISSUE TITLE
errors about the generating RGB virtual points.

### ISSUE THREAD

**Issue by ck-png** [hailanyi/VirConv#73]
When I run the python3 main.py --detpath ../../data/kitti/semi, it shows the following mistakes:
Traceback (most recent call last):
  File "/home/avl1/ck/VirConv/tools/PENet/main.py", line 482, in <module>
    main()
  File "/home/avl1/ck/VirConv/tools/PENet/main.py", line 394, in main
    iterate("test_completion", args, test_loader, model, None, logger, 0)
  File "/home/avl1/ck/VirConv/tools/PENet/main.py", line 266, in iterate
    vis_utils.save_depth_as_points(pred, i, args.detpath)
  File "/home/avl1/ck/VirConv/tools/PENet/vis_utils.py", line 150, in save_depth_as_points
    final_points = depth2pointsrgbp(depth, image, calib, lidar)
  File "/home/avl1/ck/VirConv/tools/PENet/dataloaders/my_loader.py", line 403, in depth2pointsrgbp
    new_p = la_sampling2(new_p)
  File "/home/avl1/ck/VirConv/tools/PENet/dataloaders/my_loader.py", line 251, in la_sampling2
    return np.concatenate([finals[:, 8:11], finals[:, 3:8]], -1)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by ckdghks** [comment]
Hello,
Have you resolved the issue?
If so, could you please share the solution?

**Comment by ckdghks** [comment]
I am sharing information that might be helpful to you. I resolved the issue by using the original calib.txt file from the KITTI dataset. After replacing everything with the original calib.txt data, the code ran without any issues. I hope this information helps.

**Comment by tankewudi** [comment]
Hello, I have just started working on this project. I have tried configuring the environment using this readme on both VSCode and Psycharm in the early stages, but many errors have occurred. I am currently unsure how to proceed further. Can you help me?
